apiVersion: skaffold/v2beta26
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
      - ./infra/k8s-dev/*
build:
  local:
    push: true
    # useDockerCLI: true
  # googleCloudBuild:
  #   projectId: ticketing-dev-jpj
  artifacts:
    - image: jibujacob/frontendmentorsolutions
      context: client
      docker:
        dockerfile: Dockerfile
        cliFlags:
          - --platform=linux/amd64
      sync:
        manual:
          - src: "**/*.*"
            dest: .
